package net.evarius.terranexus.election;

import com.mojang.serialization.Codec;import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.evarius.terranexus.config.ConfigManager;import net.evarius.terranexus.identity.IdentityState;
import net.minecraft.datafixer.DataFixTypes;import net.minecraft.server.MinecraftServer;import net.minecraft.server.network.ServerPlayerEntity;import net.minecraft.world.PersistentState;import net.minecraft.world.PersistentStateType;
import java.util.*;

public final class ElectionState extends PersistentState {
    private static final Codec<ElectionState> CODEC=RecordCodecBuilder.create(i->i.group(Election.CODEC.listOf().optionalFieldOf("elections",List.of()).forGetter(s->List.copyOf(s.elections.values())),Codec.unboundedMap(Codec.STRING,Codec.STRING).optionalFieldOf("offices",Map.of()).forGetter(s->s.offices),ElectionAuditEntry.CODEC.listOf().optionalFieldOf("audit",List.of()).forGetter(s->s.audit)).apply(i,ElectionState::new));
    private static final PersistentStateType<ElectionState> TYPE=new PersistentStateType<>("terranexus_elections",ElectionState::new,CODEC,DataFixTypes.LEVEL);
    private final Map<String,Election> elections=new HashMap<>();private final Map<String,String> offices=new HashMap<>();private final List<ElectionAuditEntry> audit=new ArrayList<>();
    public ElectionState(){}private ElectionState(List<Election> elections,Map<String,String> offices,List<ElectionAuditEntry> audit){elections.forEach(value->this.elections.put(value.id(),value));this.offices.putAll(offices);this.audit.addAll(audit);}
    public static ElectionState get(MinecraftServer server){return server.getOverworld().getPersistentStateManager().getOrCreate(TYPE);}
    public synchronized Election create(UUID actor,String id,String type,String title,String areaId,String role){String cleanId=normalizeId(id),cleanTitle=title==null?"":title.trim();if(cleanId.isBlank()||cleanTitle.length()<3||cleanTitle.length()>80||elections.containsKey(cleanId)||elections.size()>=ConfigManager.elections().maximumElections)return null;Election created=new Election(cleanId,type==null?"other":type.toLowerCase(Locale.ROOT),cleanTitle,areaId==null?"":areaId,Election.DRAFT,List.of(),Map.of(),actor.toString(),System.currentTimeMillis(),0,0,role==null?"":role);elections.put(cleanId,created);log(actor,"CREATE",cleanId,cleanTitle);markDirty();return created;}
    public synchronized boolean addOption(UUID actor,String id,String label,String candidateId){Election old=elections.get(id);String clean=label==null?"":label.trim();if(old==null||!old.status().equals(Election.DRAFT)||clean.length()<1||clean.length()>64||old.options().size()>=ConfigManager.elections().maximumOptions||old.options().stream().anyMatch(value->value.label().equalsIgnoreCase(clean)))return false;List<ElectionOption> options=new ArrayList<>(old.options());options.add(new ElectionOption(UUID.randomUUID().toString(),clean,candidateId==null?"":candidateId));put(old,old.status(),options,old.votes(),old.opensAt(),old.closesAt());log(actor,"OPTION",id,clean);return true;}
    public synchronized boolean open(UUID actor,String id,int durationMinutes){Election old=elections.get(id);if(old==null||!old.status().equals(Election.DRAFT)||old.options().size()<2)return false;long now=System.currentTimeMillis(),minutes=Math.max(5,Math.min(525600,durationMinutes));put(old,Election.ACTIVE,old.options(),Map.of(),now,now+minutes*60000L);log(actor,"OPEN",id,"duration="+minutes);return true;}
    public synchronized VoteResult vote(ServerPlayerEntity player,String electionId,String optionId){Election old=elections.get(electionId);long now=System.currentTimeMillis();if(old==null||!old.status().equals(Election.ACTIVE)||now<old.opensAt()||now>=old.closesAt())return new VoteResult(false,"Diese Abstimmung ist nicht aktiv.");if(IdentityState.get(player.getServer()).get(player.getUuid())==null||!IdentityState.get(player.getServer()).isApproved(player.getUuid()))return new VoteResult(false,"Nur freigeschaltete Bürger dürfen abstimmen.");if(old.votes().containsKey(player.getUuidAsString()))return new VoteResult(false,"Du hast bereits abgestimmt.");if(old.options().stream().noneMatch(value->value.id().equals(optionId)))return new VoteResult(false,"Ungültige Auswahl.");Map<String,String> votes=new HashMap<>(old.votes());votes.put(player.getUuidAsString(),optionId);put(old,old.status(),old.options(),Map.copyOf(votes),old.opensAt(),old.closesAt());log(player.getUuid(),"VOTE",electionId,"ballot-recorded");return new VoteResult(true,"Stimme wurde geheim gespeichert.");}
    public synchronized CloseResult close(UUID actor,String id){
        Election old=elections.get(id);if(old==null||!old.status().equals(Election.ACTIVE))return new CloseResult(false,"Abstimmung ist nicht aktiv.","");
        Map<String,Integer> count=new HashMap<>();old.votes().values().forEach(option->count.merge(option,1,Integer::sum));
        int maximum=count.values().stream().mapToInt(Integer::intValue).max().orElse(0);List<ElectionOption> leading=old.options().stream().filter(value->count.getOrDefault(value.id(),0)==maximum).toList();ElectionOption winner=maximum>0&&leading.size()==1?leading.getFirst():null;
        put(old,Election.CLOSED,old.options(),old.votes(),old.opensAt(),System.currentTimeMillis());
        if(winner!=null&&!old.resultingRole().isBlank()&&!winner.candidateId().isBlank())offices.put(officeKey(old.areaId(),old.resultingRole()),winner.candidateId());
        String label=winner!=null?winner.label():maximum==0?"Keine Stimmen":"Stimmengleichheit";log(actor,"CLOSE",id,"winner="+label);markDirty();return new CloseResult(true,"Abstimmung geschlossen.",label);
    }
    public synchronized List<Election> active(long now){autoCloseExpired(now);return elections.values().stream().filter(value->value.status().equals(Election.ACTIVE)).sorted(Comparator.comparingLong(Election::closesAt)).toList();}
    public Election get(String id){return elections.get(id);}public boolean holdsOffice(UUID player,String area,String role){return player.toString().equals(offices.get(officeKey(area,role)));}public List<ElectionAuditEntry> audit(){List<ElectionAuditEntry> copy=new ArrayList<>(audit);Collections.reverse(copy);return List.copyOf(copy);}
    private void autoCloseExpired(long now){for(Election value:new ArrayList<>(elections.values()))if(value.status().equals(Election.ACTIVE)&&value.closesAt()<=now)close(UUID.fromString(value.createdBy()),value.id());long oldest=now-ConfigManager.elections().completedRetentionDays*86400000L;if(elections.values().removeIf(value->value.status().equals(Election.CLOSED)&&value.closesAt()<oldest))markDirty();}
    private void put(Election old,String status,List<ElectionOption> options,Map<String,String> votes,long opens,long closes){elections.put(old.id(),new Election(old.id(),old.type(),old.title(),old.areaId(),status,List.copyOf(options),Map.copyOf(votes),old.createdBy(),old.createdAt(),opens,closes,old.resultingRole()));markDirty();}
    private void log(UUID actor,String action,String id,String details){audit.add(new ElectionAuditEntry(System.currentTimeMillis(),actor.toString(),action,id,details));int max=ConfigManager.logging().maximumLandAuditEntries;if(audit.size()>max)audit.subList(0,audit.size()-max).clear();markDirty();}
    private static String normalizeId(String value){return value==null?"":value.trim().toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_-]","");}private static String officeKey(String area,String role){return(area==null?"":area)+"|"+(role==null?"":role);}
    public record VoteResult(boolean success,String message){}public record CloseResult(boolean success,String message,String winner){}
}
