package net.evarius.terranexus.election;

import net.evarius.terranexus.management.CustomGuiService;import net.evarius.terranexus.management.ManagementHubScreen;import net.evarius.terranexus.phone.PhoneScreen;
import net.minecraft.inventory.SimpleInventory;import net.minecraft.item.Items;import net.minecraft.server.network.ServerPlayerEntity;import net.minecraft.text.Text;import net.minecraft.util.Formatting;
import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

public final class ElectionScreen {
    private static final int[] SLOTS={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43};private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").withZone(ZoneId.systemDefault());private ElectionScreen(){}
    public static void open(ServerPlayerEntity player,int requestedPage){List<Election> values=ElectionState.get(player.getServer()).active(System.currentTimeMillis());int pages=Math.max(1,(values.size()+SLOTS.length-1)/SLOTS.length),page=Math.max(0,Math.min(requestedPage,pages-1));SimpleInventory inventory=new SimpleInventory(54);Map<Integer,java.util.function.Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.BELL,Text.translatable("gui.terranexus.phone.elections"),values.isEmpty()?Text.translatable("gui.terranexus.phone.elections.empty"):Text.literal(values.size()+" aktiv"));for(int i=0;i<SLOTS.length;i++){int index=page*SLOTS.length+i;if(index>=values.size())break;Election value=values.get(index);ManagementHubScreen.display(inventory,SLOTS[i],Items.PAPER,value.title(),"Ende: "+TIME.format(Instant.ofEpochMilli(value.closesAt())));actions.put(SLOTS[i],ignored->details(player,value.id()));}if(page>0)button(inventory,actions,45,Items.ARROW,Text.translatable("gui.terranexus.previous"),ignored->open(player,page-1));if(page+1<pages)button(inventory,actions,53,Items.ARROW,Text.translatable("gui.terranexus.next"),ignored->open(player,page+1));button(inventory,actions,49,Items.BARRIER,Text.translatable("gui.terranexus.back"),ignored->PhoneScreen.open(player));CustomGuiService.open(player,inventory,actions,Text.translatable("gui.terranexus.phone.elections").formatted(Formatting.DARK_AQUA));}
    private static void details(ServerPlayerEntity player,String id){Election value=ElectionState.get(player.getServer()).get(id);if(value==null||!value.status().equals(Election.ACTIVE)){open(player,0);return;}SimpleInventory inventory=new SimpleInventory(54);Map<Integer,java.util.function.Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.BELL,value.title(),value.type()+" · bis "+TIME.format(Instant.ofEpochMilli(value.closesAt())));for(int i=0;i<Math.min(SLOTS.length,value.options().size());i++){ElectionOption option=value.options().get(i);ManagementHubScreen.display(inventory,SLOTS[i],Items.LIME_DYE,Text.literal(option.label()),Text.translatable("gui.terranexus.phone.elections.vote"));actions.put(SLOTS[i],ignored->{ElectionState.VoteResult result=ElectionState.get(player.getServer()).vote(player,id,option.id());player.sendMessage(Text.literal(result.message()).formatted(result.success()?Formatting.GREEN:Formatting.RED),false);open(player,0);});}button(inventory,actions,49,Items.ARROW,Text.translatable("gui.terranexus.back"),ignored->open(player,0));CustomGuiService.open(player,inventory,actions,Text.translatable("gui.terranexus.phone.elections").formatted(Formatting.DARK_AQUA));}
    private static void button(SimpleInventory inventory,Map<Integer,java.util.function.Consumer<net.minecraft.entity.player.PlayerEntity>> actions,int slot,net.minecraft.item.Item item,Text label,java.util.function.Consumer<net.minecraft.entity.player.PlayerEntity> action){ManagementHubScreen.display(inventory,slot,item,label,Text.empty());actions.put(slot,action);}
}
