package net.evarius.terranexus.management;

import net.evarius.terranexus.identity.*;
import net.evarius.terranexus.landlord.*;
import net.minecraft.inventory.SimpleInventory;import net.minecraft.item.Items;import net.minecraft.screen.SimpleNamedScreenHandlerFactory;import net.minecraft.server.network.ServerPlayerEntity;import net.minecraft.text.Text;import net.minecraft.util.Formatting;
import java.text.SimpleDateFormat;import java.util.*;import java.util.function.Consumer;

public final class LandSearchScreen {
    private LandSearchScreen(){}
    public static void ask(ServerPlayerEntity player){player.openHandledScreen(new SimpleNamedScreenHandlerFactory((id,inventory,ignored)->new TextInputScreenHandler(id,inventory,query->results(player,query.trim().toLowerCase(Locale.ROOT))),Text.literal("ID, Name, Adresse oder Besitzer")));}
    private static void results(ServerPlayerEntity player,String query){SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.COMPASS,"Grundstückssuche","Suchbegriff: "+query);ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Bauamt");actions.put(8,x->PropertyScreen.open(player));int slot=9;IdentityState identities=IdentityState.get(player.getServer());LandManagementState management=LandManagementState.get(player.getServer());for(LandProperty property:LandlordState.get(player.getServer()).all()){if(slot>=54)break;String owner=ownerName(identities,property),address=management.address(property.id());if(!(property.id().toLowerCase(Locale.ROOT).contains(query)||property.name().toLowerCase(Locale.ROOT).contains(query)||owner.toLowerCase(Locale.ROOT).contains(query)||address.toLowerCase(Locale.ROOT).contains(query)))continue;ManagementHubScreen.display(inventory,slot,Items.PAPER,property.name(),address+" · "+property.id()+" · "+owner);actions.put(slot++,x->PropertyFinanceScreen.open(player,property));}openMenu(player,inventory,actions,"Grundstückssuche");}
    public static void audit(ServerPlayerEntity player){if(!AuthorityState.mayAdministerLand(player))return;SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.WRITABLE_BOOK,"Grundstücksprotokoll","Letzte 45 Vorgänge · persistent");ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Bauamt");actions.put(8,x->PropertyScreen.open(player));int slot=9;SimpleDateFormat format=new SimpleDateFormat("dd.MM.yyyy HH:mm");for(LandAuditEntry entry:LandAuditState.get(player.getServer()).recent()){if(slot>=54)break;ManagementHubScreen.display(inventory,slot++,Items.PAPER,entry.action()+" · "+entry.propertyId(),format.format(new Date(entry.timestamp()))+" · "+entry.details());}openMenu(player,inventory,actions,"Audit-Log");}
    private static String ownerName(IdentityState identities,LandProperty property){if(!property.ownerType().equals("player"))return property.ownerType()+":"+property.ownerId();try{CitizenIdentity identity=identities.get(UUID.fromString(property.ownerId()));return identity==null?property.ownerId():identity.firstName()+" "+identity.lastName();}catch(Exception ignored){return property.ownerId();}}
    private static void openMenu(ServerPlayerEntity player,SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,String title){player.openHandledScreen(new SimpleNamedScreenHandlerFactory((id,pi,x)->new ActionMenuScreenHandler(id,pi,inventory,actions),Text.literal(title).formatted(Formatting.DARK_GREEN)));}
}
