package net.evarius.terranexus.management;

import net.evarius.terranexus.landlord.*;import net.minecraft.inventory.SimpleInventory;import net.minecraft.item.Items;import net.minecraft.screen.SimpleNamedScreenHandlerFactory;import net.minecraft.server.network.ServerPlayerEntity;import net.minecraft.text.Text;import net.minecraft.util.Formatting;
import java.text.SimpleDateFormat;import java.util.*;import java.util.function.Consumer;

public final class LandRegistryScreen {
    private LandRegistryScreen() {}
    public static void open(ServerPlayerEntity player){LandlordState lands=LandlordState.get(player.getServer());LandManagementState management=LandManagementState.get(player.getServer());SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.WRITTEN_BOOK,"Persönlicher Grundbuchauszug","Eigentum, private Markierungen und Vertragsangebote");int slot=9;for(LandProperty property:lands.owned(player.getUuid())){if(slot>=36)break;String marker=LandMarkerService.active(player.getUuid(),property.id())?" · Markierung "+LandMarkerService.remainingSeconds(player.getUuid(),property.id())+"s":"";button(inventory,actions,slot++,Items.PAPER,property.name(),management.address(property.id())+marker,x->details(player,property));}slot=36;for(LandSaleOffer offer:management.sales()){if(slot>=54)break;LandProperty property=lands.get(offer.propertyId());if(property==null||property.isOwnedBy(player.getUuid()))continue;button(inventory,actions,slot++,Items.EMERALD,"Kaufangebot · "+property.name(),net.evarius.terranexus.economy.EconomyState.format(offer.price()),x->PropertyFinanceScreen.open(player,property));}for(LandLease lease:management.leases()){if(slot>=54)break;if(!lease.tenantId().equals(player.getUuidAsString()))continue;LandProperty property=lands.get(lease.propertyId());if(property!=null)button(inventory,actions,slot++,Items.WRITABLE_BOOK,"Mietangebot · "+property.name(),lease.active()?"Aktiv":"Annahme erforderlich",x->PropertyFinanceScreen.open(player,property));}openMenu(player,inventory,actions,"Grundbuchauszug");}
    private static void details(ServerPlayerEntity player,LandProperty property){LandManagementState management=LandManagementState.get(player.getServer());SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.PAPER,property.name(),"ID: "+property.id()+" · "+management.address(property.id()));ManagementHubScreen.display(inventory,20,Items.COMPASS,"Lage",property.dimension()+" · "+property.minX()+","+property.minZ()+" bis "+property.maxX()+","+property.maxZ());boolean active=LandMarkerService.active(player.getUuid(),property.id());button(inventory,actions,22,active?Items.RED_DYE:Items.LIME_DYE,"GS-Markierung "+(active?"deaktivieren":"aktivieren"),active?"Nur für dich sichtbar · Restzeit "+LandMarkerService.remainingSeconds(player.getUuid(),property.id())+"s":"Automatisch aus nach 5 Minuten",x->{LandMarkerService.toggle(player,property);details(player,property);});button(inventory,actions,24,Items.GOLD_INGOT,"Verträge und Rechte","Verkauf, Vermietung und Freigaben",x->PropertyFinanceScreen.open(player,property));List<OwnershipChange> history=LandAuditState.get(player.getServer()).history(property.id());String historyText=history.isEmpty()?"Erste Eigentümereintragung":history.size()+" Wechsel · zuletzt "+new SimpleDateFormat("dd.MM.yyyy HH:mm").format(new Date(history.get(0).timestamp()));ManagementHubScreen.display(inventory,26,Items.CLOCK,"Eigentümerhistorie",historyText);ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Zum Grundbuchauszug");actions.put(8,x->open(player));openMenu(player,inventory,actions,"Grundstücksakte");}
    private static void button(SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,int slot,net.minecraft.item.Item item,String name,String detail,Consumer<net.minecraft.entity.player.PlayerEntity> action){ManagementHubScreen.display(inventory,slot,item,name,detail);actions.put(slot,action);}
    private static void openMenu(ServerPlayerEntity player,SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,String title){player.openHandledScreen(new SimpleNamedScreenHandlerFactory((id,pi,x)->new ActionMenuScreenHandler(id,pi,inventory,actions),Text.literal(title).formatted(Formatting.DARK_GREEN)));}
}
