package net.evarius.terranexus.management;

import net.evarius.terranexus.economy.EconomyState;
import net.evarius.terranexus.identity.AuthorityState;
import net.evarius.terranexus.identity.CitizenIdentity;
import net.evarius.terranexus.identity.IdentityState;
import net.evarius.terranexus.institution.InstitutionState;
import net.evarius.terranexus.landlord.*;
import net.minecraft.inventory.SimpleInventory;
import net.minecraft.item.Items;
import net.minecraft.screen.SimpleNamedScreenHandlerFactory;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.function.Consumer;

public final class PropertyFinanceScreen {
    private PropertyFinanceScreen() {}
    public static void open(ServerPlayerEntity player, LandProperty property) {
        LandManagementState management=LandManagementState.get(player.getServer());boolean manager=mayManage(player,property);SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();
        ManagementHubScreen.display(inventory,4,Items.FILLED_MAP,property.name(),"Eigentum, Miete und Zugriffsrechte");ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Zur vorherigen Übersicht");actions.put(8,ignored->back(player));
        LandSaleOffer sale=management.sale(property.id());
        if(sale==null&&manager){button(inventory,actions,10,Items.EMERALD,"Zum Verkauf anbieten","Kaufpreis eingeben",ignored->money(player,"Kaufpreis",price->{LandProperty current=LandlordState.get(player.getServer()).get(property.id());if(current==null||!mayManage(player,current)){error(player,"Berechtigung oder Eigentum hat sich geändert.");back(player);return;}management.offerSale(new LandSaleOffer(current.id(),ownerAccount(current),price,System.currentTimeMillis()));open(player,current);}));}
        else if(sale!=null){button(inventory,actions,10,Items.EMERALD,"Kaufangebot",EconomyState.format(sale.price()),ignored->{LandProperty current=LandlordState.get(player.getServer()).get(property.id());if(current!=null&&mayManage(player,current)){management.cancelSale(property.id());open(player,current);}else buy(player,property,sale);});}
        LandLease lease=management.lease(property.id());
        if(lease==null&&manager)button(inventory,actions,12,Items.WRITABLE_BOOK,"Mietangebot erstellen","Mieter, Miete, Kaution und Zeitraum",ignored->selectTenant(player,property));
        else if(lease!=null){String detail=(lease.active()?"Aktiv":"Zur Annahme")+" · "+EconomyState.format(lease.rent())+" / "+lease.periodDays()+" Tag(e) · Kaution "+EconomyState.format(lease.deposit());button(inventory,actions,12,Items.WRITTEN_BOOK,"Mietvertrag",detail,ignored->{if(!lease.active()&&lease.tenantId().equals(player.getUuidAsString()))acceptLease(player,property,lease);else if(manager)endLease(player,property,lease);});}
        LandAccess access=management.access(property.id());
        if(manager){toggle(inventory,actions,28,Items.OAK_DOOR,"Öffentliche Interaktion",access,LandAccess.INTERACT,player,property);toggle(inventory,actions,30,Items.CHEST,"Öffentliche Container",access,LandAccess.CONTAINERS,player,property);toggle(inventory,actions,32,Items.REDSTONE,"Öffentliches Redstone",access,LandAccess.REDSTONE,player,property);toggle(inventory,actions,34,Items.BRICKS,"Öffentliches Bauen",access,LandAccess.BUILD,player,property);button(inventory,actions,40,Items.NAME_TAG,"Person berechtigen","Rechte einzeln vergeben",ignored->selectTrusted(player,property));if(AuthorityState.mayAdministerLand(player))button(inventory,actions,42,Items.MAP,"Verwaltungsebene",areaLabel(management,property),ignored->LandAdministrationScreen.selectForProperty(player,property));}
        openMenu(player,inventory,actions,"Grundstück · Verträge");
    }
    private static boolean mayManage(ServerPlayerEntity p,LandProperty prop){return prop!=null&&(AuthorityState.mayProcessLandRecords(p)||prop.isOwnedBy(p.getUuid())||(prop.ownerType().equals("institution")&&InstitutionState.get(p.getServer()).mayManage(prop.ownerId(),p.getUuid())));}
    private static String ownerAccount(LandProperty p){return p.ownerType().equals("institution")?EconomyState.institutionAccount(p.ownerId()):p.ownerId();}
    private static void buy(ServerPlayerEntity buyer,LandProperty property,LandSaleOffer offer){LandlordState lands=LandlordState.get(buyer.getServer());LandManagementState management=LandManagementState.get(buyer.getServer());LandProperty current=lands.get(property.id());LandSaleOffer currentOffer=management.sale(property.id());if(current==null||currentOffer==null||currentOffer.price()!=offer.price()||!currentOffer.sellerAccount().equals(offer.sellerAccount())||!ownerAccount(current).equals(offer.sellerAccount())){error(buyer,"Dieses Kaufangebot ist nicht mehr gültig.");LandRegistryScreen.open(buyer);return;}if(EconomyState.get(buyer.getServer()).transfer(EconomyState.playerAccount(buyer.getUuid()),offer.sellerAccount(),offer.price())){lands.update(current.withOwner("player",buyer.getUuidAsString()));LandAuditState.get(buyer.getServer()).owner(buyer.getUuid(),current,"player",buyer.getUuidAsString());LandAuditState.get(buyer.getServer()).log(buyer.getUuid(),"SALE",current,EconomyState.format(offer.price()));management.cancelSale(property.id());notifyOldOwner(buyer,current);buyer.sendMessage(Text.literal("Du hast „"+current.name()+"“ gekauft.").formatted(Formatting.GREEN),false);}else error(buyer,"Nicht genügend Guthaben.");LandRegistryScreen.open(buyer);}
    private static void selectTenant(ServerPlayerEntity owner,LandProperty property){SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();int slot=9;for(CitizenIdentity identity:IdentityState.get(owner.getServer()).allApproved()){if(identity.playerUuid().equals(owner.getUuidAsString())||slot>=54)continue;String name=identity.firstName()+" "+identity.lastName();button(inventory,actions,slot++,Items.PLAYER_HEAD,name,identity.citizenNumber(),ignored->leaseMoney(owner,property,identity.playerUuid(),name));}ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Vertragsansicht");actions.put(8,ignored->open(owner,property));openMenu(owner,inventory,actions,"Mieter auswählen");}
    private static void leaseMoney(ServerPlayerEntity owner,LandProperty property,String tenantId,String tenantName){money(owner,"Miete pro Zeitraum",rent->money(owner,"Kaution",deposit->integer(owner,"Zeitraum in Tagen",days->{LandProperty current=LandlordState.get(owner.getServer()).get(property.id());if(current==null||!mayManage(owner,current)){error(owner,"Berechtigung oder Eigentum hat sich geändert.");back(owner);return;}LandManagementState.get(owner.getServer()).setLease(new LandLease(current.id(),ownerAccount(current),tenantId,rent,deposit,Math.max(1,days),0,0,false));owner.sendMessage(Text.literal("Mietangebot für "+tenantName+" wurde erstellt.").formatted(Formatting.GREEN),false);open(owner,current);})));}
    private static void acceptLease(ServerPlayerEntity tenant,LandProperty property,LandLease lease){LandManagementState management=LandManagementState.get(tenant.getServer());LandLease current=management.lease(property.id());if(current==null||current.active()||!current.tenantId().equals(tenant.getUuidAsString())||!current.equals(lease)){error(tenant,"Dieses Mietangebot ist nicht mehr gültig.");LandRegistryScreen.open(tenant);return;}EconomyState economy=EconomyState.get(tenant.getServer());if(lease.deposit()>0&&!economy.transfer(EconomyState.playerAccount(tenant.getUuid()),lease.landlordAccount(),lease.deposit())){error(tenant,"Die Kaution kann nicht bezahlt werden.");open(tenant,property);return;}management.setLease(new LandLease(lease.propertyId(),lease.landlordAccount(),lease.tenantId(),lease.rent(),lease.deposit(),lease.periodDays(),System.currentTimeMillis()+LandManagementState.periodMillis(lease.periodDays()),0,true));tenant.sendMessage(Text.literal("Mietvertrag angenommen. Du besitzt nun die Grundstücksrechte.").formatted(Formatting.GREEN),false);open(tenant,property);}
    private static void endLease(ServerPlayerEntity manager,LandProperty property,LandLease lease){if(!mayManage(manager,LandlordState.get(manager.getServer()).get(property.id()))){error(manager,"Keine aktuelle Berechtigung für diesen Vertrag.");back(manager);return;}LandLease current=LandManagementState.get(manager.getServer()).lease(property.id());if(current==null)return;if(current.active()&&current.deposit()>0)EconomyState.get(manager.getServer()).transfer(current.landlordAccount(),EconomyState.playerAccount(UUID.fromString(current.tenantId())),current.deposit());LandManagementState.get(manager.getServer()).endLease(property.id());manager.sendMessage(Text.literal("Mietvertrag beendet; eine verfügbare Kaution wurde zurückgebucht.").formatted(Formatting.YELLOW),false);open(manager,property);}
    private static void selectTrusted(ServerPlayerEntity manager,LandProperty property){LandProperty current=LandlordState.get(manager.getServer()).get(property.id());if(current==null||!mayManage(manager,current)){error(manager,"Keine aktuelle Berechtigung für dieses Grundstück.");back(manager);return;}SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();int slot=9;for(CitizenIdentity identity:IdentityState.get(manager.getServer()).allApproved()){if(slot>=54)continue;button(inventory,actions,slot++,Items.PLAYER_HEAD,identity.firstName()+" "+identity.lastName(),identity.citizenNumber(),ignored->trustedPermissions(manager,current,identity));}openMenu(manager,inventory,actions,"Person berechtigen");}
    private static void trustedPermissions(ServerPlayerEntity manager,LandProperty property,CitizenIdentity identity){LandManagementState state=LandManagementState.get(manager.getServer());LandAccess access=state.access(property.id());SimpleInventory inventory=new SimpleInventory(54);Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions=new HashMap<>();ManagementHubScreen.display(inventory,4,Items.PLAYER_HEAD,identity.firstName()+" "+identity.lastName(),"Individuelle Grundstücksrechte");individualToggle(inventory,actions,19,Items.BRICKS,"Bauen",LandAccess.BUILD,manager,property,identity,access);individualToggle(inventory,actions,21,Items.OAK_DOOR,"Interaktion",LandAccess.INTERACT,manager,property,identity,access);individualToggle(inventory,actions,23,Items.CHEST,"Container",LandAccess.CONTAINERS,manager,property,identity,access);individualToggle(inventory,actions,25,Items.REDSTONE,"Redstone",LandAccess.REDSTONE,manager,property,identity,access);ManagementHubScreen.display(inventory,8,Items.ARROW,"Zurück","Personenauswahl");actions.put(8,x->selectTrusted(manager,property));openMenu(manager,inventory,actions,"Einzelrechte");}
    private static void individualToggle(SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,int slot,net.minecraft.item.Item item,String label,String permission,ServerPlayerEntity manager,LandProperty property,CitizenIdentity identity,LandAccess access){List<String> current=access.grants().getOrDefault(identity.playerUuid(),List.of());boolean enabled=current.contains(permission);button(inventory,actions,slot,item,label,enabled?"Erlaubt":"Gesperrt",ignored->{LandProperty latestProperty=LandlordState.get(manager.getServer()).get(property.id());if(latestProperty==null||!mayManage(manager,latestProperty)){error(manager,"Berechtigung oder Eigentum hat sich geändert.");back(manager);return;}LandManagementState state=LandManagementState.get(manager.getServer());LandAccess latest=state.access(property.id());List<String> latestRules=latest.grants().getOrDefault(identity.playerUuid(),List.of());Map<String,List<String>> grants=new HashMap<>(latest.grants());List<String> changed=new ArrayList<>(latestRules);if(changed.contains(permission))changed.remove(permission);else changed.add(permission);if(changed.isEmpty())grants.remove(identity.playerUuid());else grants.put(identity.playerUuid(),changed);state.setAccess(new LandAccess(property.id(),grants,latest.publicRules()));trustedPermissions(manager,latestProperty,identity);});}
    private static void toggle(SimpleInventory inv,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,int slot,net.minecraft.item.Item item,String name,LandAccess access,String rule,ServerPlayerEntity player,LandProperty property){boolean enabled=access.publicRules().getOrDefault(rule,false);button(inv,actions,slot,item,name,enabled?"Erlaubt":"Gesperrt",ignored->{LandProperty current=LandlordState.get(player.getServer()).get(property.id());if(current==null||!mayManage(player,current)){error(player,"Berechtigung oder Eigentum hat sich geändert.");back(player);return;}LandAccess latest=LandManagementState.get(player.getServer()).access(property.id());Map<String,Boolean> rules=new HashMap<>(latest.publicRules());rules.put(rule,!latest.publicRules().getOrDefault(rule,false));LandManagementState.get(player.getServer()).setAccess(new LandAccess(property.id(),latest.grants(),rules));open(player,current);});}
    private static String areaLabel(LandManagementState state,LandProperty property){AdministrativeArea area=state.area(state.propertyArea(property.id()));return area==null?"Nicht zugeordnet":area.type()+" · "+area.name();}
    private static void money(ServerPlayerEntity player,String title,Consumer<Long> done){input(player,title,value->{try{long cents=new BigDecimal(value.replace(',','.')).movePointRight(2).setScale(0,RoundingMode.UNNECESSARY).longValueExact();if(cents<0)throw new NumberFormatException();done.accept(cents);}catch(Exception e){error(player,"Ungültiger Geldbetrag.");back(player);}});}
    private static void integer(ServerPlayerEntity player,String title,Consumer<Integer> done){input(player,title,value->{try{int parsed=Integer.parseInt(value);if(parsed<=0)throw new NumberFormatException();done.accept(parsed);}catch(Exception e){error(player,"Bitte eine positive ganze Zahl eingeben.");back(player);}});}
    private static void input(ServerPlayerEntity player,String title,Consumer<String> done){player.openHandledScreen(new SimpleNamedScreenHandlerFactory((id,inventory,ignored)->new TextInputScreenHandler(id,inventory,done),Text.literal(title)));}
    private static void error(ServerPlayerEntity player,String message){player.sendMessage(Text.literal(message).formatted(Formatting.RED),false);}
    private static void button(SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,int slot,net.minecraft.item.Item item,String name,String detail,Consumer<net.minecraft.entity.player.PlayerEntity> action){ManagementHubScreen.display(inventory,slot,item,name,detail);actions.put(slot,action);}
    private static void openMenu(ServerPlayerEntity player,SimpleInventory inventory,Map<Integer,Consumer<net.minecraft.entity.player.PlayerEntity>> actions,String title){player.openHandledScreen(new SimpleNamedScreenHandlerFactory((id,playerInventory,ignored)->new ActionMenuScreenHandler(id,playerInventory,inventory,actions),Text.literal(title).formatted(Formatting.DARK_GREEN)));}
    private static void back(ServerPlayerEntity player){if(AuthorityState.mayUseLandOffice(player))PropertyScreen.open(player);else LandRegistryScreen.open(player);}
    private static void notifyOldOwner(ServerPlayerEntity buyer,LandProperty property){if(!property.ownerType().equals("player"))return;try{ServerPlayerEntity old=buyer.getServer().getPlayerManager().getPlayer(UUID.fromString(property.ownerId()));if(old!=null)old.sendMessage(Text.literal("„"+property.name()+"“ wurde verkauft und im Grundbuch übertragen.").formatted(Formatting.GOLD),false);}catch(Exception ignored){}}
}
